LOG_FILE="/opt/var/log/keensnap.log"
PATH_SNAPD="/opt/root/KeenSnap/keensnap-init"
SCHEDULE_NAME=""
SELECTED_DRIVE=""
BOT_TOKEN=""
CHAT_ID=""
BACKUP_STARTUP_CONFIG=false
BACKUP_FIRMWARE=false
BACKUP_ENTWARE=false
BACKUP_WG_PRIVATE_KEY=false
DELETE_LOCAL_ARCHIVE_AFTER_BACKUP=false
PROXY_INTERFACE=""
TG_PROXY=""
UPLOAD_METHOD="Telegram"
GD_CLIENT_ID=""
GD_CLIENT_SECRET=""
GD_REFRESH_TOKEN=""
GD_FOLDER_ID=""
RETAIN_ARCHIVES_DAYS=0
AUTO_UPDATE=true
